# Copyright Â© 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0 or GPL-3.0-only
---
# This role configures a set of developer tools for our environment.
# Import the real tasks, in a unique file name for better navigation.
- import_tasks: awscli.yml
