# Copyright Â© 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0 or GPL-3.0-only
---
greengrass_version: 1.10.2

# Define this to download from the web rather than S3
#greengrass_package_url: "http://somewhere/greengrass-linux-x86-64-{{ greengrass_version }}.tar.gz"

greengrass_checksum: sha256:57ddc2727568a02e64f33b439d3bca563a7628b71790641d0e7354964103ea13

root_ca_checksum: sha256:eec26a7b9d62e3f674bd7befede9c878d484707a85c0702a16f54cd0704544ed

# You might define an S3 bucket to contain greengrass files.
greengrass_s3_bucket: s3-bucket-to-draw-files-from

# You'll need an ID for the core to be installed.  This should probably be set
# as a host var if you want to deploy multiple cores.
greengrass_core_id: name-of-core

# Define this to download from the web rather than S3
#greengrass_core_setup_url: http://localhost/{{ greengrass_core_setup }}

# If true, watch for an expected string in the log file to validate
# successful startup.
greengrass_wait_for_success: true

# The magic string; this may change in future core versions.
greengrass_core_success_message: Deployment agent connected to cloud
