# Copyright Â© 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
# Variables for customizing the deploy of lambda functions

lambda_role_name: "Lambda-Greengrass-S3"

lambda_role: "{{ lookup('file', 'lambda_role.json') | to_json | replace('\\n', '') }}"

aws_region: us-east-1

# An S3 bucket is required; uploading a zip directly is too slow and exceeds
# the signature threshold using the CLI.
staging_s3_bucket: greengrass-lambdas

# Set to true to bypass upload, if source is already on S3
skip_s3_uploads: false

lambdas: []
