# Copyright Â© 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
---
# Set up for running Lambdas in this account

- name: List current roles
  command: {{ aws }} iam list-roles
  register: iam_roles

- name: set lambda role fact
  set_fact:
    lambda_role_arn: "{{ iam_roles.stdout | from_json | json_query(lambda_role_query)}}"
  when: iam_roles.changed and iam_roles.rc == 0
  vars:
    lambda_role_query: "Roles[?RoleName=='Lambda-Greengrass-S3'].Arn"

- name: Create lambda role
  command: >
    {{ aws }} iam create-role --role-name Lambda-Greengrass-S3
    --assume-role-policy-document {{ lambda_role }}
  register: iam_lambda_role_create
  when: lambda_role_arn is defined and not lambda_role_arn

- name: set lambda role fact
  set_fact:
    lambda_role_arn: "{{ iam_lambda_role_create.stdout | from_json | json_query(lambda_role_query)}}"
  when: iam_lambda_role_create.changed and not lambda_role_arn
  vars:
    lambda_role_query: "Role.Arn"

- name: Attach policies to service role
  command: >
    {{ aws }} iam attach-role-policy
    --policy-arn {{ item }}
    --role-name Lambda-Greengrass-S3
  register: iam_lambda_role_attach
  with_items:
    - arn:aws:iam::aws:policy/service-role/AWSGreengrassResourceAccessRolePolicy
    - arn:aws:iam::aws:policy/AWSGreengrassFullAccess
    - arn:aws:iam::aws:policy/AmazonS3FullAccess
  when: iam_lambda_role_create.changed
