# Copyright Â© 2018 VMware, Inc. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0 or GPL-3.0-only
---
# This role installs greengrass core and configures for communication.
- name: show core to install
  debug:
    msg: "Deploying the Greengrass Core '{{ greengrass_core_id }}'."

- name: add greengrass group
  group:
    name: ggc_group
    system: yes
    state: present

- name: add greengrass user
  user:
    name: ggc_user
    system: yes
    state: present

- name: download-cgroupfs-mount
  get_url:
    url: "https://raw.githubusercontent.com/tianon/cgroupfs-mount/951c38ee8d802330454bdede20d85ec1c0f8d312/cgroupfs-mount"
    dest: /tmp/cgroupfs-mount.sh
  register: download_cgroupfs_mount
  retries: 5
  delay: 5
  until: not download_cgroupfs_mount.failed

- name: perms-cgroupfs-mount
  file:
    path: /tmp/cgroupfs-mount.sh
    mode: "+x"
  when:
    - download_cgroupfs_mount.changed
    - not download_cgroupfs_mount.failed

- name: cgroupfs-mount
  command: bash /tmp/cgroupfs-mount.sh

- name: install-pip
  package:
    name: python-pip
    state: present
  when: not ansible_check_mode

- name: install-sqlite
  package:
    name: sqlite3
    state: present
  when: not ansible_check_mode

- name: install-boto3
  pip:
    name: boto3
  when: not ansible_check_mode

- name: download-greengrass
  get_url:
    url: "{{ greengrass_package_url }}"
    dest: /tmp/greengrass-linux-x86-64-{{ greengrass_version }}.tar.gz
    checksum: "{{ greengrass_checksum }}"
  register: download_greengrass
  retries: 5
  delay: 5
  until: not download_greengrass.failed
  when: greengrass_package_url is defined

- name: download-greengrass-s3
  aws_s3:
    bucket: "{{ greengrass_s3_bucket }}"
    object: greengrass-linux-x86-64-{{ greengrass_version }}.tar.gz
    dest: /tmp/greengrass-linux-x86-64-{{ greengrass_version }}.tar.gz
    mode: get
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  when:
    - aws_access_key is defined
    - aws_secret_key is defined
    - greengrass_package_url is undefined
    - not ansible_check_mode

- file:
    path: /greengrass
    state: directory
    mode: 0755

- file:
    path: /greengrass/certs
    state: directory
    mode: 0755

- name: Check that the greengrass install archive now exists
  stat:
    path: /tmp/greengrass-linux-x86-64-{{ greengrass_version }}.tar.gz
  register: install_stat

- name: unarchive-greengrass
  unarchive:
    src: /tmp/greengrass-linux-x86-64-{{ greengrass_version }}.tar.gz
    dest: /
    remote_src: yes
  when: install_stat.stat.exists

- name: download-root-ca
  get_url:
    url: "http://www.symantec.com/content/en/us/enterprise/verisign/roots/VeriSign-Class%203-Public-Primary-Certification-Authority-G5.pem"
    dest: /greengrass/certs/root.ca.pem
    checksum: "{{ root_ca_checksum }}"
  register: download_root_ca
  retries: 5
  delay: 5
  until: not download_root_ca.failed

- name: set greengrass core setup tarball
  set_fact:
    greengrass_core_setup: "{{ greengrass_core_id }}-setup.tar.gz"
  when: greengrass_core_setup is undefined

- name: download-greengrass-config
  get_url:
    url: "{{ greengrass_core_setup_url }}"
    dest: /tmp/{{ greengrass_core_setup }}
  when: greengrass_core_setup_url is defined

- name: download-greengrass-config-s3
  aws_s3:
    bucket: "{{ greengrass_s3_bucket }}"
    object: "{{ greengrass_core_setup }}"
    dest: /tmp/{{ greengrass_core_setup }}
    mode: get
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
  when:
    - aws_access_key is defined
    - aws_secret_key is defined
    - greengrass_core_setup_url is undefined
    - not ansible_check_mode
    - not skip_s3_uploads

- name: Check that the setup file now exists
  stat:
    path: /tmp/{{ greengrass_core_setup }}
  register: setup_stat

- name: unarchive-greengrass-config
  unarchive:
    src: /tmp/{{ greengrass_core_setup }}
    dest: /greengrass
    remote_src: yes
  when: setup_stat.stat.exists

- name: copy systemd service unit
  copy:
    src: greengrassd.service
    dest: /etc/systemd/system/greengrassd.service

- name: Stop service greengrassd, if running
  service:
    name: greengrassd
    state: stopped
  when: no_greengrass_start is undefined

- name: Check for greengrass runtime log from prior installs
  stat:
    path: /greengrass/ggc/var/log/system/runtime.log
  register: runtime_log_stat

- name: Compress runtime log from prior runs, if any
  archive:
    path: /greengrass/ggc/var/log/system/runtime.log
    dest: /greengrass/ggc/var/log/system/runtime.log.tar.gz
    remove: yes
  when: runtime_log_stat.stat.exists

- name: start-greengrass
  service:
    name: greengrassd
    enabled: yes
    state: started
  when: no_greengrass_start is undefined

- name: wait for a success in the daemon log
  wait_for:
    path: /greengrass/ggc/var/log/system/runtime.log
    search_regex: "{{ greengrass_core_success_message }}"
    delay: 10
    timeout: 60
  register: wait_for_success
  when:
    - no_greengrass_start is undefined
    - greengrass_wait_for_success
